GET http://localhost:5000/
Content-Type: application/json
Author4cCI6MTYxMTMyNTg2N30.3qUyxg-8Zc0we13SEdNpl_hh2D3pFkHzOWfDe7HlD9kization: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJfaWQiOiI2MDBhZGZhMGM3NzJkNzJkYjRlZWQ4ZDYiLCJpYXQiOjE2MTEzMjU2ODcsImV